"""Generate shared built-in search/viewer protection, independently of signed lists."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POLICY = ROOT / "blocklist/web_protection.json"
DOCUMENTS = ["main_frame", "sub_frame"]
EMBEDDED = ["script", "stylesheet", "font", "image", "xmlhttprequest", "ping",
            "other", "media", "object", "websocket", "webtransport", "webbundle", "csp_report"]


def read_policy():
    policy = json.loads(POLICY.read_text())
    for key in ("blockedSearchHosts", "blockedViewerDomains"):
        domains = policy[key]
        if not isinstance(domains, list) or not domains or len(set(domains)) != len(domains):
            raise ValueError(f"{key}: expected distinct, nonempty domains")
        for domain in domains:
            if not re.fullmatch(r"[a-z0-9]+(?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9]+(?:[a-z0-9-]*[a-z0-9])?)+", domain):
                raise ValueError(f"Invalid host: {domain}")
    return policy


def outputs():
    policy = read_policy()
    hosts, viewers = policy["blockedSearchHosts"], policy["blockedViewerDomains"]
    rules = []
    # Separate bounded regexes stay under Chrome's RE2 compiled-memory limit.
    matches = [{"regexFilter": r"^https?://(?:[^/?#@]*@)?" + re.escape(h)
                + r"\.?(:[0-9]+)?([/?#]|$)"} for h in hosts]
    matches.append({"requestDomains": viewers})
    for match in matches:
        for resource_types, action in (
            (DOCUMENTS, {"type": "redirect", "redirect": {"extensionPath": "/blocked.html?reason=domain"}}),
            (EMBEDDED, {"type": "block"}),
        ):
            rules.append({"id": len(rules) + 1, "priority": 2000,
                          "action": action, "condition": {**match, "resourceTypes": resource_types}})
    safe = json.loads((ROOT / "extension/rules/safesearch.json").read_text())
    js = "// Generated by blocklist/web_protection.py. Do not edit.\n"
    js += "export const WEB_PROTECTION_RULES = " + json.dumps(rules, indent=2) + ";\n"
    js += "export const SAFESEARCH_TEMPLATES = " + json.dumps(safe, indent=2) + ";\n"
    swift = "// Generated by blocklist/web_protection.py. Do not edit.\nimport Foundation\n\n"
    swift += "enum WebProtectionPolicy {\n"
    swift += "    static let searchHosts: Set<String> = " + json.dumps(hosts) + "\n"
    swift += "    static let viewerDomains: Set<String> = " + json.dumps(viewers) + "\n\n"
    swift += """    static func isBlocked(_ raw: String) -> Bool {
        let host = raw.trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: ".")).lowercased()
        return searchHosts.contains(host) || viewerDomains.contains {
            host == $0 || host.hasSuffix("." + $0)
        }
    }
}
"""
    dns = "# Generated by blocklist/web_protection.py. Exact hosts only; the filter covers viewer subdomains.\n@0.0.0.0\n"
    dns += "\n".join(hosts + [h for d in viewers for h in (d, "www." + d)]) + "\n"
    dnsmasq = "# Generated by blocklist/web_protection.py.\n"
    dnsmasq += "".join(f"host-record={h},0.0.0.0,::\n" for h in hosts)
    dnsmasq += "".join(f"address=/{d}/0.0.0.0\naddress=/{d}/::\n" for d in viewers)
    return {
        "extension/rules/web_protection.json": json.dumps(rules, indent=2) + "\n",
        "extension/lib/web-protection.js": js,
        "macos/Hisn/WebProtectionPolicy.swift": swift,
        "macos/web_protection_hosts.txt": dns,
        "macos/web_protection_dnsmasq.conf": dnsmasq,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(name)
        else:
            path.write_text(content)
    if stale:
        parser.exit(1, "Regenerate web protection: " + ", ".join(stale) + "\n")


if __name__ == "__main__":
    main()
