// Generated by blocklist/web_protection.py. Do not edit.
import Foundation

enum WebProtectionPolicy {
    static let searchHosts: Set<String> = ["yandex.com", "www.yandex.com", "yandex.ru", "www.yandex.ru", "ya.ru", "www.ya.ru", "yandex.com.tr", "www.yandex.com.tr"]
    static let viewerDomains: Set<String> = ["nitter.net", "xcancel.com", "sotwe.com", "twstalker.com"]

    static func isBlocked(_ raw: String) -> Bool {
        let host = raw.trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: ".")).lowercased()
        return searchHosts.contains(host) || viewerDomains.contains {
            host == $0 || host.hasSuffix("." + $0)
        }
    }
}
